//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int employee_id { get; set; }
        public string f_name { get; set; }
        public string m_name { get; set; }
        public string l_name { get; set; }
        public string emp_name { get; set; }
        public string title { get; set; }
        public string employee_no { get; set; }
        public int employee_type_id { get; set; }
        public int department_id { get; set; }
        public int dept_unit_id { get; set; }
        public Nullable<int> division_id { get; set; }
        public Nullable<int> job_title_id { get; set; }
        public Nullable<int> grade_level_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> hire_date { get; set; }
        public Nullable<System.DateTime> confirm_date { get; set; }
        public string confirm_status { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public string H_address { get; set; }
        public string phone_no { get; set; }
        public string location { get; set; }
        public string state_id { get; set; }
        public string marital_status { get; set; }
        public Nullable<int> state_origin_id { get; set; }
        public string prob_period { get; set; }
        public Nullable<int> bank_id { get; set; }
        public string bank_acc_no { get; set; }
        public Nullable<int> pen_provider_id { get; set; }
        public string pen_pin { get; set; }
        public byte[] image { get; set; }
        public string quali_summ { get; set; }
        public string email { get; set; }
        public string email2 { get; set; }
        public Nullable<System.DateTime> wed_anni_date { get; set; }
        public Nullable<int> no_child { get; set; }
        public string hobby { get; set; }
        public Nullable<int> branch_id { get; set; }
        public Nullable<double> salary_annual { get; set; }
    
        public virtual bank bank { get; set; }
        public virtual comp_branch comp_branch { get; set; }
        public virtual company company { get; set; }
        public virtual department department { get; set; }
        public virtual dept_units dept_units { get; set; }
        public virtual division division { get; set; }
        public virtual employee_type employee_type { get; set; }
        public virtual grade_level grade_level { get; set; }
        public virtual job_title job_title { get; set; }
        public virtual pen_providers pen_providers { get; set; }
    }
}
