//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HumanResourceEntities : DbContext
    {
        public HumanResourceEntities()
            : base("name=HumanResourceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bank> banks { get; set; }
        public virtual DbSet<cadre> cadres { get; set; }
        public virtual DbSet<comp_branch> comp_branch { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<dept_units> dept_units { get; set; }
        public virtual DbSet<division> divisions { get; set; }
        public virtual DbSet<employee_type> employee_type { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<grade> grades { get; set; }
        public virtual DbSet<grade_level> grade_level { get; set; }
        public virtual DbSet<job_class> job_class { get; set; }
        public virtual DbSet<job_title> job_title { get; set; }
        public virtual DbSet<pen_providers> pen_providers { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<step> steps { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
